# Generated by Django 6.0.7 on 2026-07-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('process', 'Process'), ('payment', 'Payment'), ('refund', 'Refund'), ('print', 'Print'), ('download', 'Download'), ('system', 'System'), ('other', 'Other')], max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_log_a_created_ff4321_idx'), models.Index(fields=['user', 'created_at'], name='audit_log_a_user_id_6ee8ec_idx'), models.Index(fields=['tenant', 'created_at'], name='audit_log_a_tenant__fa1779_idx'), models.Index(fields=['action'], name='audit_log_a_action_903622_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_log_a_model_n_8e90fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('log_all_actions', models.BooleanField(default=True)),
                ('log_reads', models.BooleanField(default=False)),
                ('log_writes', models.BooleanField(default=True)),
                ('log_auth', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('auto_cleanup', models.BooleanField(default=True)),
                ('excluded_models', models.TextField(blank=True, help_text='Comma separated list of models to exclude (e.g., auth.User, auth.Group)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Audit Log Settings',
                'verbose_name_plural': 'Audit Log Settings',
                'indexes': [models.Index(fields=['tenant'], name='audit_log_a_tenant__3cf89f_idx')],
            },
        ),
    ]
