# Generated by Django 6.0.7 on 2026-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("process", "Process"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("print", "Print"),
                            ("download", "Download"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("log_all_actions", models.BooleanField(default=True)),
                ("log_reads", models.BooleanField(default=False)),
                ("log_writes", models.BooleanField(default=True)),
                ("log_auth", models.BooleanField(default=True)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("auto_cleanup", models.BooleanField(default=True)),
                (
                    "excluded_models",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated list of models to exclude (e.g., auth.User, auth.Group)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Log Settings",
                "verbose_name_plural": "Audit Log Settings",
            },
        ),
    ]
