# Generated by Django 6.0.6 on 2026-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0003_initial'),
        ('tenants', '0003_alter_subscriptioninvoice_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlogsettings',
            index=models.Index(fields=['tenant'], name='audit_log_a_tenant__3cf89f_idx'),
        ),
    ]
