# Generated by Django 6.0.7 on 2026-07-08 13:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('last_synced', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Offline Cache',
                'verbose_name_plural': 'Offline Caches',
                'ordering': ['-last_synced'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fa-building', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('plan', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit Card'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Branch Transfer'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCING', 'Sync in Progress'), ('SYNCED', 'Synced Successfully'), ('FAILED', 'Sync Failed'), ('CONFLICT', 'Conflict Detected')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('conflict_resolved', models.BooleanField(default=False)),
                ('resolved_data', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Queue Entry',
                'verbose_name_plural': 'Sync Queue Entries',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_pin', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Upload company logo (PNG, JPG, JPEG - Max 5MB)', null=True, upload_to='tenant_logos/')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paybill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('show_till_number', models.BooleanField(default=True)),
                ('show_paybill', models.BooleanField(default=True)),
                ('show_account_number', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(blank=True, help_text='Code of the current subscription plan', max_length=50, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, help_text='Start date of current subscription', null=True)),
                ('subscription_end', models.DateTimeField(blank=True, help_text='End date of current subscription', null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('max_users', models.IntegerField(default=5)),
                ('max_products', models.IntegerField(default=100)),
                ('max_branches', models.IntegerField(default=1)),
                ('max_storage_gb', models.IntegerField(default=1)),
                ('max_rooms', models.IntegerField(default=20, help_text='Maximum rooms for Hotel Master')),
                ('features', models.JSONField(default=dict)),
                ('icon', models.CharField(default='fa-building', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'price_monthly'],
                'indexes': [models.Index(fields=['code'], name='tenants_sub_code_6c33ea_idx'), models.Index(fields=['is_active'], name='tenants_sub_is_acti_00fc63_idx')],
            },
        ),
    ]
