# Generated by Django 6.0.6 on 2026-06-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.projecttype'),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offlinecache',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_cache', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['tenant', 'synced'], name='tenants_syn_tenant__dcf11e_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['created_at'], name='tenants_syn_created_bab245_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['model_name', 'object_id'], name='tenants_syn_model_n_f2ffc2_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinecache',
            index=models.Index(fields=['tenant', 'model_name'], name='tenants_off_tenant__0cb94b_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinecache',
            index=models.Index(fields=['last_synced'], name='tenants_off_last_sy_b9ec8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offlinecache',
            unique_together={('tenant', 'model_name', 'object_id')},
        ),
    ]
