# Generated by Django 6.0.7 on 2026-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
