# Generated by Django 6.0.6 on 2026-06-22 18:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['tenant', 'status'], name='tenants_sub_tenant__7690f7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['invoice_number'], name='tenants_sub_invoice_30b2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['created_at'], name='tenants_sub_created_88a5be_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['code'], name='tenants_sub_code_6c33ea_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active'], name='tenants_sub_is_acti_00fc63_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code'], name='tenants_ten_code_64b1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
    ]
