# Generated by Django 6.0.6 on 2026-06-23 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_subscriptioninvoice_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncqueue',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': 'Sync Queue Entry', 'verbose_name_plural': 'Sync Queue Entries'},
        ),
        migrations.RemoveIndex(
            model_name='syncqueue',
            name='tenants_syn_tenant__dcf11e_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncqueue',
            name='tenants_syn_created_bab245_idx',
        ),
        migrations.RenameField(
            model_name='syncqueue',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='syncqueue',
            old_name='synced_at',
            new_name='last_attempt',
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='conflict_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='max_retries',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='previous_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sync_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='resolved_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCING', 'Sync in Progress'), ('SYNCED', 'Synced Successfully'), ('FAILED', 'Sync Failed'), ('CONFLICT', 'Conflict Detected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='operation',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Branch Transfer'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['tenant', 'status'], name='tenants_syn_tenant__46e717_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['status', 'created_at'], name='tenants_syn_status_8eb9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['tenant', 'priority'], name='tenants_syn_tenant__6c9009_idx'),
        ),
        migrations.RemoveField(
            model_name='syncqueue',
            name='synced',
        ),
    ]
