# Generated by Django 6.0.7 on 2026-07-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_master', '0002_alter_product_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this user is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tech_master.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date when the user was hired', null=True),
        ),
    ]
