# Generated by Django 6.0.6 on 2026-06-23 12:50

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_syncqueue_options_and_more'),
        ('users', '0002_user_users_user_tenant__b5ba35_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('sale', 'Sale Created'), ('return', 'Return Created'), ('stock_update', 'Stock Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('password_change', 'Password Changed'), ('pin_change', 'PIN Changed'), ('role_change', 'Role Changed'), ('tenant_switch', 'Tenant Switched')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_usera_user_id_113a56_idx'), models.Index(fields=['tenant', 'action'], name='users_usera_tenant__49d65c_idx'), models.Index(fields=['created_at'], name='users_usera_created_281045_idx'), models.Index(fields=['tenant', 'created_at'], name='users_usera_tenant__d1165e_idx')],
            },
        ),
    ]
