# Generated by Django 6.0.6 on 2026-06-23 13:00

import apps.shared.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.shared.users.models.UserManager()),
            ],
        ),
    ]
