# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_master', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hardwareproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hardware_master.hardwarecategory'),
        ),
        migrations.AddField(
            model_name='hardwareproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_products', to='tenants.tenant'),
        ),
    ]
