# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_master', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaresale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hardwaresale',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_sales', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hardwaresaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_master.hardwareproduct'),
        ),
        migrations.AddField(
            model_name='hardwaresaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware_master.hardwaresale'),
        ),
        migrations.AddField(
            model_name='hardwarestockentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hardwarestockentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='hardware_master.hardwareproduct'),
        ),
        migrations.AddField(
            model_name='hardwarestockentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_stock_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hardwaresupplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_suppliers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hardwarestockentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware_master.hardwaresupplier'),
        ),
        migrations.AlterUniqueTogether(
            name='hardwarecategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='hardwareproduct',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='hardwaresupplier',
            unique_together={('tenant', 'name')},
        ),
    ]
