# Generated by Django 6.0.7 on 2026-07-15 23:31

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FashionBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("boutique", "Boutique"),
                            ("department_store", "Department Store"),
                            ("outlet", "Outlet"),
                            ("pop_up", "Pop-up Store"),
                            ("showroom", "Showroom"),
                            ("warehouse", "Warehouse"),
                        ],
                        default="boutique",
                        max_length=50,
                    ),
                ),
                ("has_fitting_rooms", models.BooleanField(default=True)),
                ("has_tailor_services", models.BooleanField(default=False)),
                ("has_alteration_services", models.BooleanField(default=False)),
                (
                    "specializes_in",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Women's Wear, Men's Wear, Children's Wear",
                        max_length=200,
                    ),
                ),
                (
                    "store_ambiance",
                    models.TextField(
                        blank=True, help_text="Store theme, decor, music, etc."
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("sunday_opening", models.TimeField(blank=True, null=True)),
                ("sunday_closing", models.TimeField(blank=True, null=True)),
                ("is_holiday_open", models.BooleanField(default=False)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("instagram_handle", models.CharField(blank=True, max_length=100)),
                ("facebook_page", models.CharField(blank=True, max_length=200)),
                (
                    "total_floor_space",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total floor space in sq ft", null=True
                    ),
                ),
                ("fitting_rooms_count", models.PositiveIntegerField(default=2)),
                ("cash_registers", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fashion Branch",
                "verbose_name_plural": "Fashion Branches",
            },
        ),
        migrations.CreateModel(
            name="FashionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("shoes", "Shoes"),
                            ("bedding", "Bedding"),
                            ("cosmetics", "Cosmetics"),
                            ("boutique", "Boutique"),
                            ("babyshop", "Baby Shop"),
                            ("accessories", "Accessories"),
                            ("bags", "Bags"),
                            ("jewelry", "Jewelry"),
                            ("watches", "Watches"),
                            ("other", "Other"),
                        ],
                        default="clothing",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("unisex", "Unisex"),
                            ("kids", "Kids"),
                            ("babies", "Babies"),
                        ],
                        default="unisex",
                        max_length=20,
                    ),
                ),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing Sizes (S, M, L, XL, XXL)"),
                            ("shoes", "Shoe Sizes (35-45)"),
                            ("bedding", "Bedding Sizes (Single, Double, Queen, King)"),
                            ("baby", "Baby Sizes (0-3, 3-6, 6-9, 9-12, 12-18, 18-24)"),
                            ("generic", "Generic Sizes"),
                            ("none", "No Size (Cosmetics, Accessories)"),
                        ],
                        default="clothing",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tenant", "category_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FashionCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("year", models.PositiveIntegerField(help_text="Collection year")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("fall", "Fall"),
                            ("winter", "Winter"),
                            ("holiday", "Holiday"),
                            ("resort", "Resort"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FashionInventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("damage", "Damage/Loss"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Positive for IN, Negative for OUT"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Invoice, PO, or reference number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FashionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_code", models.CharField(db_index=True, max_length=50)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "size",
                    models.CharField(
                        blank=True, help_text="e.g., S, M, L, 38, 40", max_length=20
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("material", models.CharField(blank=True, max_length=100)),
                (
                    "buying_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "best_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                ("damaged_quantity", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Summer, Winter, Spring, Fall",
                        max_length=50,
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        blank=True, help_text="Collection name", max_length=100
                    ),
                ),
                ("style_code", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fashion_products/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=100)),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="fashion_products/"
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="fashion_products/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_discontinued", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_new_arrival", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tenant", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FashionReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New/Unused"),
                            ("worn", "Worn/Used"),
                            ("defective", "Defective"),
                            ("damaged", "Damaged"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FashionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "permissions",
                    models.JSONField(
                        default=list, help_text="List of permission codenames"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_role", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="FashionSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "invoice_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("card", "Card"),
                            ("bank", "Bank Transfer"),
                            ("mobile", "Mobile Money"),
                            ("credit", "Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "change_given",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="FashionSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_size", models.CharField(blank=True, max_length=20)),
                ("product_color", models.CharField(blank=True, max_length=50)),
                ("product_sku", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FashionStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Store Manager"),
                            ("sales_rep", "Sales Representative"),
                            ("stylist", "Fashion Stylist"),
                            ("cashier", "Cashier"),
                            ("stock_controller", "Stock Controller"),
                            ("visual_merchandiser", "Visual Merchandiser"),
                            ("tailor", "Tailor"),
                            ("other", "Other"),
                        ],
                        default="sales_rep",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="4-digit PIN for POS access",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "expertise",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Women's Wear, Men's Wear, Children's Wear",
                        max_length=200,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Commission rate for sales",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Fashion Staff",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FashionStaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("leave", "On Leave"),
                            ("holiday", "Holiday"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("check_in_location", models.CharField(blank=True, max_length=255)),
                ("check_out_location", models.CharField(blank=True, max_length=255)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fashion Staff Attendance",
                "verbose_name_plural": "Fashion Staff Attendances",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FashionStaffLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fashion Staff Leave",
                "verbose_name_plural": "Fashion Staff Leaves",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FashionStoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(blank=True, max_length=200)),
                ("store_phone", models.CharField(blank=True, max_length=20)),
                ("store_email", models.EmailField(blank=True, max_length=254)),
                ("store_address", models.TextField(blank=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("16.00"), max_digits=5
                    ),
                ),
                ("is_tax_inclusive", models.BooleanField(default=True)),
                ("enable_loyalty", models.BooleanField(default=False)),
                (
                    "points_per_100",
                    models.PositiveIntegerField(
                        default=10, help_text="Points earned per 100 KES spent"
                    ),
                ),
                ("show_logo_on_receipt", models.BooleanField(default=True)),
                (
                    "footer_message",
                    models.CharField(
                        blank=True,
                        default="Thank you for shopping with us!",
                        max_length=200,
                    ),
                ),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("auto_restock_level", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FashionVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=50)),
                ("sku", models.CharField(db_index=True, max_length=50)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "buying_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fashion_variants/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product", "size", "color"],
            },
        ),
    ]
