# Generated by Django 6.0.7 on 2026-07-15 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fashion_master", "0001_initial"),
        ("tronic_master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fashionbranch",
            name="branch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_settings",
                to="tronic_master.branch",
            ),
        ),
    ]
