# Generated by Django 6.0.7 on 2026-07-10 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('tech_master', 'Tech Master'), ('food_master', 'Food Master'), ('hotel_master', 'Hotel Master'), ('retail_master', 'Retail Master'), ('health_master', 'Health Master'), ('fashion_master', 'Fashion Master'), ('rental_master', 'Rental_Master')], default='tech_master', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission codenames')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='tenants.tenant')),
                ('users', models.ManyToManyField(blank=True, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant', 'project_type', 'name'],
                'unique_together': {('tenant', 'project_type', 'name')},
            },
        ),
    ]
