# Generated by Django 6.0.7 on 2026-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('tronic_master', 'Tech Master'), ('food_master', 'Food Master'), ('hotel_master', 'Hotel Master'), ('retail_master', 'Retail Master'), ('health_master', 'Health Master'), ('fashion_master', 'Fashion Master'), ('rental_master', 'Rental_Master')], default='tronic_master', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission codenames')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tenant', 'project_type', 'name'],
            },
        ),
    ]
