# Generated by Django 6.0.7 on 2026-07-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['tenant', 'sku_code'], 'permissions': [('can_view_product', 'Can view products'), ('can_add_product', 'Can add products'), ('can_edit_product', 'Can edit products'), ('can_delete_product', 'Can delete products'), ('can_manage_product', 'Can manage products'), ('can_view_category', 'Can view categories'), ('can_add_category', 'Can add categories'), ('can_edit_category', 'Can edit categories'), ('can_delete_category', 'Can delete categories'), ('can_view_branch', 'Can view branches'), ('can_add_branch', 'Can add branches'), ('can_edit_branch', 'Can edit branches'), ('can_delete_branch', 'Can delete branches'), ('can_manage_branch', 'Can manage branches'), ('can_view_supplier', 'Can view suppliers'), ('can_add_supplier', 'Can add suppliers'), ('can_edit_supplier', 'Can edit suppliers'), ('can_delete_supplier', 'Can delete suppliers'), ('can_view_stock', 'Can view stock'), ('can_manage_stock', 'Can manage stock'), ('can_adjust_stock', 'Can adjust stock'), ('can_view_low_stock', 'Can view low stock alerts'), ('can_view_sale', 'Can view sales'), ('can_create_sale', 'Can create sales'), ('can_edit_sale', 'Can edit sales'), ('can_delete_sale', 'Can delete sales'), ('can_process_payment', 'Can process payments'), ('can_view_receipt', 'Can view receipts'), ('can_view_staff', 'Can view staff'), ('can_add_staff', 'Can add staff'), ('can_edit_staff', 'Can edit staff'), ('can_delete_staff', 'Can delete staff'), ('can_manage_staff', 'Can manage staff'), ('can_view_report', 'Can view reports'), ('can_export_report', 'Can export reports'), ('can_view_settings', 'Can view settings'), ('can_manage_settings', 'Can manage settings')], 'verbose_name': 'Product SKU', 'verbose_name_plural': 'Product SKUs'},
        ),
    ]
