# Generated by Django 6.0.6 on 2026-06-22 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user'], name='notificatio_user_id_0299fd_idx'),
        ),
    ]
