# Generated by Django 6.0.7 on 2026-07-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('role_type', models.CharField(choices=[('system', 'System Role'), ('custom', 'Custom Role')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='permissions.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission')),
                ('project_types', models.ManyToManyField(blank=True, help_text='Project types this role is applicable to (leave blank for all)', related_name='roles', to='tenants.projecttype')),
                ('users', models.ManyToManyField(blank=True, related_name='custom_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add/Create'), ('change', 'Change/Edit'), ('delete', 'Delete'), ('manage', 'Manage/Full Control'), ('export', 'Export'), ('import', 'Import'), ('print', 'Print'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('revoke', 'Revoke')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text="e.g., 'products', 'users', 'sales'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_permission', to='auth.permission')),
            ],
            options={
                'verbose_name': 'System Permission',
                'verbose_name_plural': 'System Permissions',
                'ordering': ['category', 'action'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='permissions.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['codename'], name='permissions_codenam_4c4599_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='permissions_is_acti_c1045d_idx'),
        ),
        migrations.AddIndex(
            model_name='systempermission',
            index=models.Index(fields=['action'], name='permissions_action_437cba_idx'),
        ),
        migrations.AddIndex(
            model_name='systempermission',
            index=models.Index(fields=['category'], name='permissions_categor_6b435c_idx'),
        ),
        migrations.AddIndex(
            model_name='systempermission',
            index=models.Index(fields=['is_active'], name='permissions_is_acti_2f7dbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role')},
        ),
    ]
