# Generated by Django 6.0.7 on 2026-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='project_types',
            field=models.ManyToManyField(blank=True, help_text='Project types this role is applicable to (leave blank for all)', related_name='roles', to='tenants.projecttype'),
        ),
    ]
