# Generated by Django 6.0.7 on 2026-07-15 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="custom_roles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="systempermission",
            name="django_permission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_permission",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["codename"], name="permissions_codenam_4c4599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_c1045d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systempermission",
            index=models.Index(fields=["action"], name="permissions_action_437cba_idx"),
        ),
        migrations.AddIndex(
            model_name="systempermission",
            index=models.Index(
                fields=["category"], name="permissions_categor_6b435c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systempermission",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_2f7dbd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroleassignment",
            unique_together={("user", "role")},
        ),
    ]
