# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='expenses_ex_tenant__675493_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['tenant', 'name'], name='expenses_ex_tenant__4ac6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'status'], name='expenses_ex_tenant__fe23ee_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'date'], name='expenses_ex_tenant__6b7e91_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'category'], name='expenses_ex_tenant__23afcd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'created_at'], name='expenses_ex_tenant__994418_idx'),
        ),
    ]
