# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_master', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food_master.branch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food_master.customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reservations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='food_master.branch'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_staff', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='food_master.branch'),
        ),
        migrations.AddField(
            model_name='table',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_tables', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='food_master.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='food_master.table'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'purchase_date'], name='food_master_tenant__40cbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'category'], name='food_master_tenant__d5e2be_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'item_name'], name='food_master_tenant__ea0448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('tenant', 'branch', 'table_number')},
        ),
    ]
