# Generated by Django 6.0.6 on 2026-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('date_format', models.CharField(default='Y-m-d', max_length=20)),
                ('time_format', models.CharField(default='H:i', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notify_on_sale', models.BooleanField(default=True)),
                ('notify_on_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_address', models.TextField(blank=True, default='')),
                ('business_phone', models.CharField(blank=True, default='', max_length=20)),
                ('business_email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_tax_pin', models.CharField(blank=True, default='', max_length=50)),
                ('show_business_name', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_tax_pin', models.BooleanField(default=True)),
                ('show_receipt_number', models.BooleanField(default=True)),
                ('show_sale_date', models.BooleanField(default=True)),
                ('show_sale_time', models.BooleanField(default=True)),
                ('show_agent_user', models.BooleanField(default=True)),
                ('show_buyer_name', models.BooleanField(default=True)),
                ('show_buyer_phone', models.BooleanField(default=True)),
                ('show_buyer_id', models.BooleanField(default=True)),
                ('show_next_of_kin_name', models.BooleanField(default=True)),
                ('show_next_of_kin_phone', models.BooleanField(default=True)),
                ('show_items_table', models.BooleanField(default=True)),
                ('show_imei', models.BooleanField(default=True)),
                ('show_quantity', models.BooleanField(default=True)),
                ('show_unit_price', models.BooleanField(default=True)),
                ('show_line_total', models.BooleanField(default=True)),
                ('show_gross_total', models.BooleanField(default=True)),
                ('show_footer_message', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, default='Thank you for your business!', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
