# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_settings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='tenants.tenant'),
        ),
    ]
