# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptsetting',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_settings', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['key'], name='settings_sy_key_d49ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='companysetting',
            index=models.Index(fields=['tenant'], name='settings_co_tenant__342101_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelsetting',
            unique_together={('tenant',)},
        ),
        migrations.AddIndex(
            model_name='paymentsetting',
            index=models.Index(fields=['tenant'], name='settings_pa_tenant__7bfc42_idx'),
        ),
        migrations.AddIndex(
            model_name='profilesetting',
            index=models.Index(fields=['user'], name='settings_pr_user_id_e9eb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptsetting',
            index=models.Index(fields=['tenant'], name='settings_re_tenant__179b9e_idx'),
        ),
    ]
