# Generated by Django 6.0.6 on 2026-06-22 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        ('tenants', '0003_alter_subscriptioninvoice_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesetting',
            options={'verbose_name': 'Profile Setting', 'verbose_name_plural': 'Profile Settings'},
        ),
        migrations.AlterModelOptions(
            name='receiptsetting',
            options={'verbose_name': 'Receipt Setting', 'verbose_name_plural': 'Receipt Settings'},
        ),
        migrations.AddIndex(
            model_name='profilesetting',
            index=models.Index(fields=['user'], name='settings_pr_user_id_e9eb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptsetting',
            index=models.Index(fields=['tenant'], name='settings_re_tenant__179b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['key'], name='settings_sy_key_d49ddf_idx'),
        ),
    ]
