# Generated by Django 6.0.7 on 2026-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='enable_slideshow',
            field=models.BooleanField(default=True, help_text='Enable slideshow on dashboard'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_text_1',
            field=models.CharField(blank=True, default='', help_text='Button text for slide 1', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_text_2',
            field=models.CharField(blank=True, default='', help_text='Button text for slide 2', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_text_3',
            field=models.CharField(blank=True, default='', help_text='Button text for slide 3', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_text_4',
            field=models.CharField(blank=True, default='', help_text='Button text for slide 4', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_text_5',
            field=models.CharField(blank=True, default='', help_text='Button text for slide 5', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_url_1',
            field=models.CharField(blank=True, default='', help_text='Button URL for slide 1', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_url_2',
            field=models.CharField(blank=True, default='', help_text='Button URL for slide 2', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_url_3',
            field=models.CharField(blank=True, default='', help_text='Button URL for slide 3', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_url_4',
            field=models.CharField(blank=True, default='', help_text='Button URL for slide 4', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_button_url_5',
            field=models.CharField(blank=True, default='', help_text='Button URL for slide 5', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_image_1',
            field=models.ImageField(blank=True, help_text='Slide 1 - Upload image (recommended: 1920x1080)', null=True, upload_to='company_slides/'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_image_2',
            field=models.ImageField(blank=True, help_text='Slide 2 - Upload image (recommended: 1920x1080)', null=True, upload_to='company_slides/'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_image_3',
            field=models.ImageField(blank=True, help_text='Slide 3 - Upload image (recommended: 1920x1080)', null=True, upload_to='company_slides/'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_image_4',
            field=models.ImageField(blank=True, help_text='Slide 4 - Upload image (recommended: 1920x1080)', null=True, upload_to='company_slides/'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_image_5',
            field=models.ImageField(blank=True, help_text='Slide 5 - Upload image (recommended: 1920x1080)', null=True, upload_to='company_slides/'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_subtitle_1',
            field=models.CharField(blank=True, default='', help_text='Subtitle for slide 1', max_length=300),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_subtitle_2',
            field=models.CharField(blank=True, default='', help_text='Subtitle for slide 2', max_length=300),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_subtitle_3',
            field=models.CharField(blank=True, default='', help_text='Subtitle for slide 3', max_length=300),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_subtitle_4',
            field=models.CharField(blank=True, default='', help_text='Subtitle for slide 4', max_length=300),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_subtitle_5',
            field=models.CharField(blank=True, default='', help_text='Subtitle for slide 5', max_length=300),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_title_1',
            field=models.CharField(blank=True, default='', help_text='Title for slide 1', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_title_2',
            field=models.CharField(blank=True, default='', help_text='Title for slide 2', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_title_3',
            field=models.CharField(blank=True, default='', help_text='Title for slide 3', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_title_4',
            field=models.CharField(blank=True, default='', help_text='Title for slide 4', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slide_title_5',
            field=models.CharField(blank=True, default='', help_text='Title for slide 5', max_length=200),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='slideshow_interval',
            field=models.IntegerField(default=5000, help_text='Slideshow interval in milliseconds (e.g., 5000 = 5 seconds)'),
        ),
    ]
