# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linquor_master', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquor_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='liquorproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='linquor_master.liquorcategory'),
        ),
        migrations.AddField(
            model_name='liquorproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquor_products', to='tenants.tenant'),
        ),
    ]
