# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linquor_master', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorsale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquor_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquorsale',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquor_sales', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='liquorcategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='liquorproduct',
            unique_together={('tenant', 'sku')},
        ),
    ]
