# Generated by Django 6.0.6 on 2026-06-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawer',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdrawer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashier.cashdrawer'),
        ),
    ]
