# Generated by Django 6.0.6 on 2026-06-22 18:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_initial'),
        ('inventory', '0002_initial'),
        ('tenants', '0003_alter_subscriptioninvoice_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['tenant', 'is_open'], name='cashier_cas_tenant__28161f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['cashier', 'is_open'], name='cashier_cas_cashier_e09924_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['tenant', 'opened_at'], name='cashier_cas_tenant__13291c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['drawer', 'transaction_type'], name='cashier_cas_drawer__c63c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['drawer', 'created_at'], name='cashier_cas_drawer__52913f_idx'),
        ),
    ]
