# Generated by Django 6.0.6 on 2026-06-22 18:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('tenants', '0003_alter_subscriptioninvoice_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'status'], name='expenses_ex_tenant__fe23ee_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'date'], name='expenses_ex_tenant__6b7e91_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'category'], name='expenses_ex_tenant__23afcd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'created_at'], name='expenses_ex_tenant__994418_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='expenses_ex_tenant__675493_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['tenant', 'name'], name='expenses_ex_tenant__4ac6c9_idx'),
        ),
    ]
