# Generated by Django 6.0.7 on 2026-07-15 23:31

import datetime
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Main Store, Mombasa Branch, Warehouse A",
                        max_length=200,
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique branch code per tenant (e.g., MAIN, MSA, WARE-A)",
                        max_length=50,
                        verbose_name="Branch Code",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Physical Address"),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/County"
                    ),
                ),
                ("country", models.CharField(default="Kenya", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Store"),
                            ("sub_branch", "Sub-Branch"),
                            ("warehouse", "Warehouse"),
                            ("outlet", "Outlet"),
                            ("kiosk", "Kiosk"),
                        ],
                        default="sub_branch",
                        max_length=20,
                        verbose_name="Branch Type",
                    ),
                ),
                (
                    "is_main_branch",
                    models.BooleanField(
                        default=False,
                        help_text="Only one branch per tenant can be the main branch",
                        verbose_name="Is Main Branch?",
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the branch manager",
                        max_length=200,
                        verbose_name="Branch Manager",
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_24_hours", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="BranchStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch Stock",
                "verbose_name_plural": "Branch Stocks",
            },
        ),
        migrations.CreateModel(
            name="BranchTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("received_date", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Branch Transfer",
                "verbose_name_plural": "Branch Transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="CashDrawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "closing_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("single", "Single Item"), ("bulk", "Bulk Item")],
                        max_length=10,
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("imei", "IMEI Number (15-digit)"),
                            ("serial", "Serial Number"),
                            ("none", "No Unique Identifier"),
                        ],
                        default="imei",
                        max_length=10,
                    ),
                ),
                ("category_code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice Counter",
                "verbose_name_plural": "Invoice Counters",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique product code per tenant (e.g., 000001, 000002 or custom)",
                        max_length=50,
                        verbose_name="SKU Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Display name (auto-generated if blank)",
                        max_length=255,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Brand"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Model"
                    ),
                ),
                (
                    "default_buying_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Default Buying Price (KES)",
                    ),
                ),
                (
                    "default_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Default Selling Price (KES)",
                    ),
                ),
                (
                    "default_best_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Default Best/Retail Price (KES)",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Quantity (All Variants)"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Available Quantity (All Variants)"
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reserved Quantity (All Variants)"
                    ),
                ),
                (
                    "damaged_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Damaged Quantity (All Variants)"
                    ),
                ),
                ("reorder_level", models.PositiveIntegerField(default=5)),
                ("warranty_months", models.PositiveIntegerField(default=12)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Product Image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_discontinued", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["tenant", "brand", "model"],
            },
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_branch_transfer_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "imei_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        null=True,
                        verbose_name="IMEI Number",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "unit_buying_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Buying Price",
                    ),
                ),
                (
                    "unit_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Selling Price",
                    ),
                ),
                (
                    "best_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="whosale price for this specific unit (market price)",
                        max_digits=12,
                        null=True,
                        verbose_name="Best/wholesale Price",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assigned Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("damaged", "Damaged"),
                            ("stolen", "Stolen"),
                            ("lost", "Lost"),
                            ("returned", "Returned"),
                            ("writeoff", "Written Off"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("refurbished", "Refurbished"),
                            ("used_excellent", "Used - Excellent"),
                            ("used_good", "Used - Good"),
                            ("used_fair", "Used - Fair"),
                            ("damaged", "Damaged"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "sold_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Sold At Price",
                    ),
                ),
                ("sold_date", models.DateTimeField(blank=True, null=True)),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "warranty_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warranty_end", models.DateTimeField(blank=True, null=True)),
                (
                    "loss_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stolen", "Stolen"),
                            ("lost", "Lost"),
                            ("damaged_total", "Totally Damaged"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("loss_reported_date", models.DateTimeField(blank=True, null=True)),
                ("loss_notes", models.TextField(blank=True, null=True)),
                (
                    "police_report_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("insurance_claim_filed", models.BooleanField(default=False)),
                (
                    "insurance_claim_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "insurance_claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "insurance_payout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("insurance_payout_date", models.DateTimeField(blank=True, null=True)),
                ("recovered_date", models.DateTimeField(blank=True, null=True)),
                ("recovery_notes", models.TextField(blank=True, null=True)),
                (
                    "warehouse_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shelf_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Unit",
                "verbose_name_plural": "Product Units",
                "ordering": ["product__sku_code", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_sku",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: SKU-RAM-STORAGE-COLOR",
                        max_length=100,
                        unique=True,
                        verbose_name="Variant SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RAM, storage, color, etc. Example: {'ram': '4GB', 'storage': '64GB', 'color': 'Black'}",
                        verbose_name="Specifications",
                    ),
                ),
                (
                    "buying_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use product default",
                        max_digits=12,
                        null=True,
                        verbose_name="Buying Price (KES)",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use product default",
                        max_digits=12,
                        null=True,
                        verbose_name="Selling Price (KES)",
                    ),
                ),
                (
                    "best_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Best/Retail Price (KES)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Quantity"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Available Quantity"
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reserved Quantity"
                    ),
                ),
                (
                    "damaged_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Damaged Quantity"
                    ),
                ),
                (
                    "imei_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        null=True,
                        verbose_name="IMEI Number",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("damaged", "Damaged"),
                            ("stolen", "Stolen"),
                            ("lost", "Lost"),
                            ("returned", "Returned"),
                            ("writeoff", "Written Off"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("refurbished", "Refurbished"),
                            ("used_excellent", "Used - Excellent"),
                            ("used_good", "Used - Good"),
                            ("used_fair", "Used - Fair"),
                            ("damaged", "Damaged"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                ("reorder_level", models.PositiveIntegerField(default=5)),
                ("warranty_months", models.PositiveIntegerField(default=12)),
                (
                    "sold_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Sold At Price",
                    ),
                ),
                ("sold_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assigned Date"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "warranty_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warranty_end", models.DateTimeField(blank=True, null=True)),
                (
                    "warehouse_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shelf_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "loss_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stolen", "Stolen"),
                            ("lost", "Lost"),
                            ("damaged_total", "Totally Damaged"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("loss_reported_date", models.DateTimeField(blank=True, null=True)),
                ("loss_notes", models.TextField(blank=True, null=True)),
                (
                    "police_report_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("insurance_claim_filed", models.BooleanField(default=False)),
                (
                    "insurance_claim_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "insurance_claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "insurance_payout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("insurance_payout_date", models.DateTimeField(blank=True, null=True)),
                ("recovered_date", models.DateTimeField(blank=True, null=True)),
                ("recovery_notes", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["product__brand", "product__model", "variant_sku"],
            },
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "invoice_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank Transfer"),
                            ("card", "Card"),
                            ("mobile", "Mobile Money"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("tax_inclusive", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("cashier", "Cashier"),
                            ("sales_agent", "Sales Agent"),
                            ("stock_controller", "Stock Controller"),
                            ("technician", "Technician"),
                            ("cleaner", "Cleaner"),
                            ("other", "Other"),
                        ],
                        default="cashier",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="4-digit PIN for POS access",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Staff",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("leave", "On Leave"),
                            ("holiday", "Holiday"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("check_in_location", models.CharField(blank=True, max_length=255)),
                ("check_out_location", models.CharField(blank=True, max_length=255)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Attendance",
                "verbose_name_plural": "Staff Attendances",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Leave",
                "verbose_name_plural": "Staff Leaves",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("lowstock", "Low Stock"),
                            ("needs_reorder", "Needs Reorder"),
                            ("outofstock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("threshold", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stock Alert",
                "verbose_name_plural": "Stock Alerts",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for stock IN, Negative for stock OUT"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("reversal", "Reversal / Return"),
                            ("adjustment", "Manual Adjustment"),
                            ("damage", "Damaged Write-off"),
                            ("theft", "Theft/Loss"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stock Entry",
                "verbose_name_plural": "Stock Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["tenant", "name"],
            },
        ),
    ]
