# Generated by Django 6.0.7 on 2026-07-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('tenants', '0002_initial'),
        ('tronic_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='transferred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdrawer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='cashdrawer',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdrawer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tronic_master.cashdrawer'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoicecounter',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_counter', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tronic_master.branch', verbose_name='Default Branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tronic_master.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='tronic_master.product'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_units', to='tronic_master.branch', verbose_name='Current Branch Location'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='current_owner',
            field=models.ForeignKey(blank=True, help_text='Sales agent currently assigned to this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='loss_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_unit_losses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tronic_master.product', verbose_name='Product SKU'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='recovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='transferred_from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_units', to='tronic_master.branch', verbose_name='Transferred From Branch'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='tronic_master.productunit'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_variants', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='tronic_master.branch', verbose_name='Default Branch'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='current_owner',
            field=models.ForeignKey(blank=True, help_text='Sales agent currently assigned to this variant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_variants', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='loss_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_variant_losses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tronic_master.product', verbose_name='Parent Product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tronic_master.product'),
        ),
        migrations.AddField(
            model_name='return',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tronic_master.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='tronic_master.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='tronic_master.productunit'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tronic_master.sale'),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tech_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tronic_master.staff'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff_attendances', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tech_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tech_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='tronic_master.staff'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff_leaves', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tronic_master.product'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='tronic_master.branch'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='tronic_master.product'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='tronic_master.productunit'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='tronic_master.supplier'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tronic_master.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tronic_master.supplier', verbose_name='Supplier'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'code'], name='tronic_mast_tenant__ce7e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'is_active'], name='tronic_mast_tenant__5a8214_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'branch_type'], name='tronic_mast_tenant__8bf0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_main_branch'], name='tronic_mast_is_main_010cb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['tenant', 'is_open'], name='tronic_mast_tenant__f0d7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['cashier', 'is_open'], name='tronic_mast_cashier_62ffb9_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['tenant', 'opened_at'], name='tronic_mast_tenant__758d57_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['drawer', 'transaction_type'], name='tronic_mast_drawer__189704_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['drawer', 'created_at'], name='tronic_mast_drawer__cd46da_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'name'], name='tronic_mast_tenant__d77081_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'category_code'], name='tronic_mast_tenant__2b3e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'category_code'), ('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='invoicecounter',
            index=models.Index(fields=['tenant'], name='tronic_mast_tenant__5df184_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'product'], name='tronic_mast_branch__0cf85f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['tenant', 'branch'], name='tronic_mast_tenant__5f9fe2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('branch', 'product')},
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['status'], name='tronic_mast_status_7cc69f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['from_branch', 'to_branch'], name='tronic_mast_from_br_b6eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['tenant', 'status'], name='tronic_mast_tenant__4a3b17_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'invoice_no'], name='tronic_mast_tenant__49c9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'status'], name='tronic_mast_tenant__e1b142_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'created_at'], name='tronic_mast_tenant__ad0c38_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['tenant', 'status'], name='tronic_mast_tenant__25cff6_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale', 'product'], name='tronic_mast_sale_id_ecc7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['tenant', 'created_at'], name='tronic_mast_tenant__76b9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tenant', 'branch'], name='tronic_mast_tenant__2db260_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='tronic_mast_role_67ac0b_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='tronic_mast_is_acti_86eb0c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='tronic_mast_staff_i_5755c9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['tenant', 'date'], name='tronic_mast_tenant__cfbb87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='staffleave',
            index=models.Index(fields=['staff', 'status'], name='tronic_mast_staff_i_fda725_idx'),
        ),
        migrations.AddIndex(
            model_name='staffleave',
            index=models.Index(fields=['tenant', 'status'], name='tronic_mast_tenant__46db40_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['tenant', 'product', 'is_active'], name='tronic_mast_tenant__94c6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type'], name='tronic_mast_alert_t_750608_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['-created_at'], name='tronic_mast_created_ca3371_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['entry_type'], name='tronic_mast_entry_t_a747b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['tenant', 'branch'], name='tronic_mast_tenant__3fbc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product_sku', '-created_at'], name='tronic_mast_product_1759e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'variant_sku'], name='tronic_mast_tenant__362579_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'product'], name='tronic_mast_tenant__6fcf03_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'imei_number'], name='tronic_mast_tenant__66b30d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'serial_number'], name='tronic_mast_tenant__770705_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['status'], name='tronic_mast_status_298406_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'status'], name='tronic_mast_product_73c2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['branch', 'status'], name='tronic_mast_branch__374e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['current_owner', 'status'], name='tronic_mast_current_159bf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('tenant', 'variant_sku')},
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['tenant', 'imei_number'], name='tronic_mast_tenant__183d88_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['tenant', 'serial_number'], name='tronic_mast_tenant__cdc9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['status'], name='tronic_mast_status_72f806_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', 'status'], name='tronic_mast_product_8e45dc_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['branch', 'status'], name='tronic_mast_branch__fa07fe_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['current_owner', 'status'], name='tronic_mast_current_3ae429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together={('tenant', 'imei_number'), ('tenant', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'sku_code'], name='tronic_mast_tenant__240fce_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'brand', 'model'], name='tronic_mast_tenant__c788a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='tronic_mast_tenant__9d00e0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'available_quantity'], name='tronic_mast_tenant__97ed53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'brand', 'model'), ('tenant', 'sku_code')},
        ),
    ]
