# Generated by Django 6.0.7 on 2026-07-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
        ('tronic_master', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff_attendances', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tronic_staff_leaves', to='tenants.tenant'),
        ),
    ]
