# Generated by Django 6.0.7 on 2026-07-19 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('tenants', '0002_initial'),
        ('tronic_master', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('pos', 'Point of Sale'), ('agent', 'Sales Agent'), ('admin', 'Admin'), ('online', 'Online'), ('bulk', 'Bulk Sale')], default='agent', help_text='Source of the sale (POS, Agent, Admin, etc.)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'source'], name='tronic_mast_tenant__b15350_idx'),
        ),
    ]
