# Generated by Django 6.0.7 on 2026-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
        ('tronic_master', '0003_add_sale_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Invoice Number'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('tenant', 'invoice_no')},
        ),
    ]
