# Generated by Django 6.0.7 on 2026-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tronic_master', '0004_fix_invoice_unique_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Optional barcode for scanning at POS', max_length=100, null=True, verbose_name='Barcode'),
        ),
    ]
